target-version = "py310"

include = ["pyproject.toml", "src/**/*.py", "scripts/**/*.py", "src/**/*.ipynb"]

exclude = [
    "**/test/**",
]


[lint]
select = ["ALL"]
ignore = [
    "D100",
    "D105", # Function doc for every function
    "S101",
    "INP001", # __init__ for implicit namespace
    "T201", # No print,
    "E501", # Line too long
    
    # About TODO
    "TD002",
    "TD003",
    "FIX002",
]

[lint.flake8-quotes]
inline-quotes = "double"

[format]
docstring-code-format = true
