from typing import Literal

MEMORY_LEVELS = Literal["LTM", "STM"]

CATEGORIES = [
    "USER INFO",
    "ALZ INFO",
    "CARE RECIPIENT INFO",
    "CARE PROVIDER INFO",
    "CARE PROVIDER RELATIONSHIP",
    "CARE RECIPIENT RELATIONSHIP",
    "CARE PROVIDER RELATIONSHIP",
]